import { Link } from "react-router-dom";

const HomePage = () => (
  <div className="overflow-hidden bg-white">
    <section className="relative isolate"><div className="absolute inset-x-0 top-0 -z-10 h-[35rem] bg-[radial-gradient(circle_at_15%_20%,rgba(191,219,254,.8),transparent_28rem),radial-gradient(circle_at_85%_25%,rgba(221,214,254,.72),transparent_25rem),linear-gradient(180deg,#f8fbff_0%,#fff_100%)]" /><div className="mx-auto grid max-w-7xl gap-14 px-6 pb-20 pt-16 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-10 lg:pb-28 lg:pt-24"><div className="max-w-2xl"><div className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white/80 px-3 py-1.5 text-sm font-medium text-blue-700 shadow-sm backdrop-blur"><span className="size-2 rounded-full bg-emerald-500" /> Guest print ordering</div><h1 className="mt-6 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">Upload at the shop link.<span className="block text-blue-600">Collect with four digits.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">CloudPrint gives every print shop its own URL. Students can upload a document as guests — no registration, password, or student dashboard required.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#how-it-works" className="inline-flex items-center justify-center rounded-xl bg-blue-600 px-5 py-3.5 text-sm font-semibold text-white shadow-lg shadow-blue-600/25 transition hover:bg-blue-700">See the guest flow</a><Link to="/auth/login" className="inline-flex items-center justify-center rounded-xl border border-slate-200 bg-white px-5 py-3.5 text-sm font-semibold text-slate-700 transition hover:border-slate-300 hover:bg-slate-50">Shop owner sign in</Link></div></div><div className="relative mx-auto w-full max-w-md"><div className="absolute -inset-5 -z-10 rounded-[2.5rem] bg-blue-200/45 blur-3xl" /><div className="rounded-[2rem] border border-white/80 bg-white p-5 shadow-2xl shadow-slate-300/50"><div className="rounded-[1.45rem] bg-slate-950 p-6 text-white"><p className="text-xs font-bold tracking-[.16em] text-blue-200 uppercase">Guest confirmation</p><h2 className="mt-2 text-xl font-bold">Your order is with Campus Copy Centre</h2><div className="mt-6 rounded-2xl bg-white/10 p-4 text-center"><p className="text-xs font-semibold tracking-[.16em] text-slate-300 uppercase">Pickup code</p><p className="mt-2 font-mono text-4xl font-bold tracking-[.28em]">4821</p></div><p className="mt-5 text-sm leading-6 text-slate-300">Show this code at the counter to collect your printout.</p></div><div className="grid grid-cols-3 gap-3 px-1 pt-4 text-center"><div><p className="text-lg font-bold text-slate-900">0</p><p className="text-xs text-slate-500">accounts</p></div><div className="border-x border-slate-100"><p className="text-lg font-bold text-slate-900">4</p><p className="text-xs text-slate-500">digits</p></div><div><p className="text-lg font-bold text-slate-900">1</p><p className="text-xs text-slate-500">shop link</p></div></div></div></div></div></section>
    <section id="how-it-works" className="border-y border-slate-100 bg-slate-50/70 py-20 sm:py-24"><div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-sm font-bold tracking-[.16em] text-blue-600 uppercase">Simple by design</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">One clear flow from file to counter.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-4">{[["1", "Admin creates the shop", "Choose the shop name, owner account, and unique URL."], ["2", "Student opens the URL", "Share it directly or turn it into a QR code at the counter."], ["3", "Student uploads as a guest", "Add a PDF, Office document, or image, then select print options."], ["4", "Shop processes the order", "The dashboard shows the file and a four-digit pickup code."]].map(([number, title, description]) => <article key={number} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><span className="flex size-10 items-center justify-center rounded-xl bg-blue-600 text-sm font-bold text-white">{number}</span><h3 className="mt-6 text-lg font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></article>)}</div></div></section>
    <section id="services" className="py-20 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-6 sm:px-8 lg:grid-cols-2 lg:px-10"><div><p className="text-sm font-bold tracking-[.16em] text-blue-600 uppercase">Built for print shops</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Files go only to the selected shop.</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">Every order is tied to the URL a student used. Shop owners can download the document, view print preferences, and advance the order from submitted through collection.</p></div><div className="rounded-3xl bg-slate-950 p-8 text-white"><p className="text-sm font-bold tracking-[.16em] text-blue-200 uppercase">For staff</p><h3 className="mt-3 text-2xl font-bold">A focused dashboard, not a student portal.</h3><ul className="mt-6 space-y-3 text-sm leading-6 text-slate-300"><li>• Download submitted files securely</li><li>• See copies, colour, sides, and finishing choices</li><li>• Move orders through printing and pickup</li><li>• Match the collection using a four-digit code</li></ul><Link to="/auth/login" className="mt-7 inline-flex rounded-xl bg-white px-4 py-3 text-sm font-semibold text-slate-950 hover:bg-blue-50">Sign in to the shop dashboard</Link></div></div></section>
  </div>
);

export default HomePage;
